### PR TITLE
Unbind tooltip remove focus listeners

### LINKED ISSUE #9071: unbindTooltip does not remove focus listeners
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Open this [jsfiddle link](https://jsfiddle.net/bielfrontera/50Lcfs96/8/)
2. Wait two seconds until the tooltip is unbinded
3. Click on the the marker. You'll see this error message at the browser console:
``` 
Tooltip.js:399 Uncaught TypeError: Cannot set properties of null (setting '_source')
    at e.<anonymous> (Tooltip.js:399:19)
    at SVGPathElement.o (DomEvent.js:108:13)
```

### Expected behavior

After the tooltip is unbinded, focus listeners should be removed (or at least, that listener should ensure that `this._tooltip` is not `null`)

### Current behavior

An error is raised if you click on a layer with an unbinded tooltip. 

### Minimal example reproducing the issue

https://jsfiddle.net/bielfrontera/50Lcfs96/8/

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Google Chrome v 115.0.5790.170
- OS/Platform (with version): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by hollowM1ke**
My solution for fixes #9071

### CODE REVIEW

**Review by Falke-Design — CHANGES_REQUESTED** [review]
Thank you for trying to solve this issue but this solution causes other tests to fail. Please make sure to test if all the tests are successfull. You can do this with `npm run test`

grafik

**Comment by hollowM1ke** [comment]
@Falke-Design it is really strange. So I've run `npm run test` on my branch and I get the following:
error1

Then I wanted to see if I get any errors on the main branch. And I get this:
error2

Would there be a reason this happens?

**Comment by Falke-Design** [comment]
Did you do a re-build? `npm run watch`

**Comment by hollowM1ke** [comment]
> Did you do a re-build? `npm run watch`

I've done `npm run build` and then `npm run test`. Should I do `npm run test` and then `npm run watch`?

**Comment by hollowM1ke** [comment]
> > Did you do a re-build? `npm run watch`
> 
> I've done `npm run build` and then `npm run test`. Should I do `npm run test` and then `npm run watch`?
If yes then I am not sure how, because whenever I run `npm run test` it doesn't terminate, I have to force cancel it.

**Comment by Falke-Design** [comment]
no, you did it correct. First build and then test.

I will check it the next days by myself. In the mean time you can merge the latest commit from `main` into your branch

File: src/layer/Tooltip.js [hunk 1]
```diff
@@ -385,22 +385,38 @@ Layer.include({
...
-			}, this);
-			DomEvent.on(el, 'blur', this.closeTooltip, this);
+		if (layer.getElement) {
+			const el = layer.getElement();
+			if (el) {
+				DomEvent.on(el, 'focus', function () {
+					this._tooltip._source = layer;
+					this.openTooltip();
+				}, this);
+				DomEvent.on(el, 'blur', this.closeTooltip, this);
```
Comment (Falke-Design) [inline src/layer/Tooltip.js:418]: We should remove the events here too

File: src/layer/Tooltip.js [hunk 2]
```diff
@@ -385,22 +385,38 @@ Layer.include({
...
 
+	_handleFocus() {
+		this._tooltip._source = this;
+		this.openTooltip();
+	},
+
+	_handleBlur() {
+		this.closeTooltip();
+	},
+
```
Comment (Falke-Design) [inline src/layer/Tooltip.js:409]: Code exists twice: here and in `_addFocusListenersOnLayer`

**Review by Falke-Design — CHANGES_REQUESTED** [review]
Looks better now 😄 
Can you please try to add a test which covers your changes

**Comment by hollowM1ke** [comment]
Hi @Falke-Design, could I get an update?

File: src/layer/Tooltip.js [hunk 3]
```diff
@@ -385,22 +385,38 @@ Layer.include({
...
+	_addFocusListenersOnLayer(layer, remove) {
+		if (layer.getElement) {
+			const el = layer.getElement();
+			if (el) {
+				const onOff = remove ? 'off' : 'on';
+				DomEvent[onOff](el, 'focus', () => this._handleFocus(layer), this);
+				DomEvent[onOff](el, 'blur', this._handleBlur, this);
+			}
 		}
```
Comment (Falke-Design) [inline src/layer/Tooltip.js:420]: I think we should do the following (or something similar if there is a better way):

1. `_addFocusListeners` does the same for a element as `_addFocusListenersOnLayer`, so we don't duplicate the code.
2. Then the `_handleBlur` don't need to be a function anymore, because we can call `closeTooltip` directly
3. We store the `named` function / listener (`el._leaflet_focus_handler`) for the focus on the element, because an anonymous function / listener can't be removed with `off`

```
	_addFocusListeners(remove) {
		if (this.getElement) {
			this._addFocusListenersOnLayer(this, remove);
		} else if (this.eachLayer && this._map.getRenderer(this)) {
			this.eachLayer(layer => this._addFocusListenersOnLayer(layer, remove), this);
		}
	},

	_addFocusListenersOnLayer(layer, remove) {
		const el = typeof layer.getElement === 'function' && layer.getElement();
		if (el) {
			const onOff = remove ? 'off' : 'on';
			if (!remove) {
				// Remove focus listener, if already existing
				el._leaflet_focus_handler && DomEvent.off(el, 'focus', el._leaflet_focus_handler, this);

				el._leaflet_focus_handler = () => {
					if (this._tooltip) {
						this._tooltip._source = layer;
						this.openTooltip();
					}
				};
			}

			el._leaflet_focus_handler && DomEvent[onOff](el, 'focus', el._leaflet_focus_handler, this);
			DomEvent[onOff](el, 'blur', this.closeTooltip, this);

			if (remove) {
				delete el._leaflet_focus_handler;
			}
		}
	},
```

File: spec/suites/layer/TooltipSpec.js [hunk 4]
```diff
@@ -578,4 +578,22 @@ describe('Tooltip', () => {
...
+		  .bindTooltip('Tooltip that will be unbinded in two seconds')
+		  .openTooltip();
+
+		marker.unbindTooltip();
+
+		setTimeout(() => {
+			expect(() => UIEventSimulator.fire('focus', marker.getElement())).to.not.throw();
+		}, 2000);
+	});
 });
```
Comment (Falke-Design) [inline spec/suites/layer/TooltipSpec.js:599]: Please add a test for a LayerGroup too:

```
const marker = new Marker(latlng);

			var lg = new LayerGroup([marker]).addTo(map);

			lg
				.bindTooltip('Tooltip that will be unbinded in two seconds')
				.openTooltip()
				.unbindTooltip();
```

File: spec/suites/layer/TooltipSpec.js [hunk 5]
```diff
@@ -578,4 +578,22 @@ describe('Tooltip', () => {
...
+
+		marker
+		  .bindTooltip('Tooltip that will be unbinded in two seconds')
+		  .openTooltip();
+
+		marker.unbindTooltip();
+
+		setTimeout(() => {
+			expect(() => UIEventSimulator.fire('focus', marker.getElement())).to.not.throw();
+		}, 2000);
```
Comment (Falke-Design) [inline spec/suites/layer/TooltipSpec.js:597]: We should not wait so long. Maximum of 500ms is allowed, better is earlier

**Review by Falke-Design — CHANGES_REQUESTED** [review]
Sorry for letting you wait so long. 
I rewrote the functions, what do you think about it?

File: src/layer/Tooltip.js [hunk 6]
```diff
@@ -385,22 +385,37 @@ Layer.include({
...
 	},
 
-	_addFocusListeners() {
+	_addFocusListeners(remove) {
 		if (this.getElement) {
-			this._addFocusListenersOnLayer(this);
-		} else if (this.eachLayer) {
-			this.eachLayer(this._addFocusListenersOnLayer, this);
+			this._addFocusListenersOnLayer(this, remove);
+		} else if (this.eachLayer && this._map.getRenderer(this)) {
```
Comment (Falke-Design) [inline src/layer/Tooltip.js:391]:
```suggestion
```

File: src/layer/Tooltip.js [hunk 7]
```diff
@@ -385,22 +385,36 @@ Layer.include({
...
 	},
 
-	_addFocusListeners() {
+	_addFocusListeners(remove) {
 		if (this.getElement) {
-			this._addFocusListenersOnLayer(this);
-		} else if (this.eachLayer) {
-			this.eachLayer(this._addFocusListenersOnLayer, this);
+			this._addFocusListenersOnLayer(this, remove);
+			this.eachLayer(layer => this._addFocusListenersOnLayer(layer, remove), this);
```
Comment (Falke-Design) [inline src/layer/Tooltip.js:391]:
```suggestion
		} else if (this.eachLayer) {
			this.eachLayer(layer => this._addFocusListenersOnLayer(layer, remove), this);
```

**Review by Falke-Design — APPROVED** [review]
