### PR TITLE
Locate - locationfound: Add check if map container has leaflet_id / is existing

### LINKED ISSUE #7508: _handleGeolocationResponse: exception when map is already removed
See #2001

Seeing this error at 

[./src/dom/DomUtil.js:247](https://github.com/Leaflet/Leaflet/blob/0f904a515879fcd08f69b7f51799ee7f18f23fd8/src/dom/DomUtil.js#L247):	`return el._leaflet_pos || new Point(0, 0);`

### PR DESCRIPTION
**Pull request by Falke-Design**
If the map is removed before the location is found, it throwed an error. Now it checks if the map container has the leaflet_id else it returns.

Fix #7508

### CODE REVIEW

File: src/map/Map.js [hunk 1]
```diff
@@ -665,6 +665,8 @@ export var Map = Evented.extend({
 	},
 
 	_handleGeolocationError: function (error) {
+		if (!this.getContainer()._leaflet_id) { return; }
```
Comment (johnd0e) [inline src/map/Map.js:668]: Perhaps here we can safely use private `_container` property.

File: spec/suites/map/MapSpec.js [hunk 2]
```diff
@@ -1318,4 +1318,14 @@ describe("Map", function () {
 			expect(map.getZoom()).to.be(undefined);
 		});
 	});
+
+	describe("#Geolocation", function () {
+		it("don't throw error if location is found and map is not existing", function () {
+			var fn = L.Util.bind(map._handleGeolocationResponse, map);
```
Comment (johnd0e) [inline spec/suites/map/MapSpec.js:1324]: Perhaps you should ass location error test as well

Comment (Falke-Design) [reply spec/suites/map/MapSpec.js:1324]: Have you an idea how to test? I don't throw an error so I can't catch them

Comment (Falke-Design) [reply spec/suites/map/MapSpec.js:1324]: Maybe I can listen if the `locationerror` event is fired

Comment (johnd0e) [reply spec/suites/map/MapSpec.js:1324]: > Have you an idea how to test?

In the same manner - call `_handleGeolocationError` and check it does not throw.

Comment (Falke-Design) [reply spec/suites/map/MapSpec.js:1324]: `_handleGeolocationError` doesn't throw an error, so I can't catch it

Comment (johnd0e) [reply spec/suites/map/MapSpec.js:1324]: Even if `setView` option is used?

Comment (Falke-Design) [reply spec/suites/map/MapSpec.js:1324]: You are right. I have tested it wrong (while map initialisation I set center and zoom) and then setView was not called, because the map was already loaded.

File: spec/suites/map/MapSpec.js [hunk 3]
```diff
@@ -1318,4 +1318,22 @@ describe("Map", function () {
 			expect(map.getZoom()).to.be(undefined);
 		});
 	});
+
+	describe("#Geolocation", function () {
+		it("don't throw error if location is found and map is not existing", function () {
```
Comment (johnd0e) [inline spec/suites/map/MapSpec.js:1323]:
```suggestion
		it("doesn't throw error if location is found and map is not existing", function () {
```

File: spec/suites/map/MapSpec.js [hunk 4]
```diff
@@ -1318,4 +1318,22 @@ describe("Map", function () {
...
+			var fn = L.Util.bind(map._handleGeolocationResponse, map);
+			map.remove();
+			expect(function () {
+				fn({coords: {latitude: 40.415296, longitude: 10.7419264, accuracy: 1129.5646101470752}});
+			}).to.not.throwException();
+		});
+		it("don't throw error if location is not found and map is not existing", function () {
```
Comment (johnd0e) [inline spec/suites/map/MapSpec.js:1330]:
```suggestion
		it("doesn't throw error if location is not found and map is not existing", function () {
```

**Review by johnd0e — CHANGES_REQUESTED** [review]

**Review by johnd0e — APPROVED** [review]
