### PR TITLE
Fix intermittent wobble when setMaxBounds(map.getBounds())

### LINKED ISSUE #8532: Map shaking after setMaxBounds and setMinZoom
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Create a map.
2. Set its maximum borders and minimum zoom to those currently visible on the screen.

`const map = L.map('map').setView([50.450036, 30.5241361], 13)`

`L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {`
`    attribution:`
`        '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',`
`}).addTo(map)`

`map.setMaxBounds(map.getBounds()).setMinZoom(map.getZoom())`

### Expected behavior

The map is limited by the maximum borders and the minimum zoom without any unexpected behavior.

### Current behavior

Map is limited by the maximum borders and the minimum zoom, but the map is moving (shaking).
I have looked at these issues: #[1946](https://github.com/Leaflet/Leaflet/pull/1946), #[2107](https://github.com/Leaflet/Leaflet/issues/2107), #[2011](https://github.com/Leaflet/Leaflet/issues/2011), #[2081](https://github.com/Leaflet/Leaflet/issues/2081), #[1866](https://github.com/Leaflet/Leaflet/issues/1866), #[2187](https://github.com/Leaflet/Leaflet/pull/2187). But it seems that there is no solution to my problem there, so I don't think it's a duplicate to any of previous issues. If it is, could you please help me to resolve this issue?
Thank you!

### Minimal example reproducing the issue

https://jsfiddle.net/fd3mertj/1/

### Environment

- Leaflet version:  1.8.0, 1.9.1
- Browser (with version): Mozilla 105.0.1 (64 bit), Opera 90.0.4480.84
- OS/Platform (with version): Windows 10 laptop

### PR DESCRIPTION
**Pull request by rjackson**
Fixes #8532

At certain coordinate and/or screen size combinations, `Map.setMaxBounds` ended up triggering an infinite `_panInsideMaxBounds` loop due to slight discrepancies in reprojected center points across loops.

We are supposed to break out of this loop if our recalculated centers are identical:

https://github.com/Leaflet/Leaflet/blob/4372a9fcadce23d23a21370439179c09d1118ab3/src/map/Map.js#L503-L514

And our `_limitCenter` code was already set up to catch subpixel offsets, ignore them, and returning the identical center to break the loop.

Unfortunately it seems the projection instability can cause up to 1px offsets, which this code was not catching.

This PR adds a failing test for the problem as reported, using the `setView` values from the bug report. This test does appear to consistently fail.

The PR also updates `_limitCenter` to ignore up to 1 pixel offsets, which fixes the issue.

### CODE REVIEW

File: spec/suites/map/MapSpec.js [hunk 1]
```diff
@@ -458,6 +458,20 @@ describe("Map", function () {
 			map.setMaxBounds(bounds, {animate: false});
 			expect(map.off.called).not.to.be.ok();
 		});
+
+		it("avoid subpixel / floating point related wobble (#8532)", function (done) {
+			map.setView([50.450036, 30.5241361], 13);
+
+			var spy = sinon.spy();
+			map.on('moveend', spy);
```
Comment (mourner) [inline spec/suites/map/MapSpec.js:466]: Should be `once` so that it doesn't pollute other tests, right?
```suggestion
			map.once('moveend', spy);
```

**Review by Falke-Design — APPROVED** [review]
Very nice!

**Review by mourner — APPROVED** [review]
Looks good to me!

File: spec/suites/map/MapSpec.js (hunk 1 above)
Comment (mourner) [reply spec/suites/map/MapSpec.js:466]: Ah right.
