### PR TITLE
Bugfix: refocus map after using layers control (#9004)

### LINKED ISSUE #9004: Map loses focus after clicking on map controls - reprise
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. click on an item in the layers control
2. try using +/- keyboard keys to zoom

### Expected behavior

The map should be refocused after using layers control.

### Current behavior

The map loses focus after using layers control.

In 2013, #2148 / 254e6fe6b9a6350cf2ee50ca8f6465bc433ac96e added code so that if you use button controls the map gets refocused, so that keyboard keys like +/- still work.

However, later in 2015,  #3275 / 8842385c376a6ba14573f85b38e7b6fe8e05e7ba broke this.  It intended to make `_refocusOnMap` only apply when it was triggered by a keyboard event, but the commit had the effect of making it _never_ apply, because the commit added a parameter to the function, without passing it at call time.

### Minimal example reproducing the issue

https://leafletjs.com/examples/layers-control/

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Chrome 114.0.5735.133, Firefox 113.0
- OS/Platform (with version): MacOS 13.2.1

### PR DESCRIPTION
**Pull request by quarl**
Fixes #9004

### CODE REVIEW

**Review by mourner — COMMENTED** [review]
Really nice catch, thanks for submitting a fix — looks good to me! How easy would it be to add a test case for this so that the behavior doesn't regress again in the future?

File: src/control/Control.js [hunk 1]
```diff
@@ -104,8 +104,9 @@ export const Control = Class.extend({
 	},
 
 	_refocusOnMap(e) {
-		// if map exists and event is not a keyboard event
-		if (this._map && e && e.screenX > 0 && e.screenY > 0) {
+		// We exclude keyboard-click event to keep the focus on the control for accessibility.
+		// The position of keyboard-click events are x=0 and y=0.
+		if (this._map && e && !(e.screenX === 0 && e.screenY === 0)) {
```
Comment (Falke-Design) [inline src/control/Control.js:109]: I changed this check because `e.screenX > 0 && e.screenY > 0` didn't worked on my second screen because `screenX` was `-1700`

**Review by Falke-Design — COMMENTED** [review]
I added a test and also changed the screen coord check.

**Review by Falke-Design — APPROVED** [review]
