### PR TITLE
Stop click on _openPopup

### LINKED ISSUE #3604: Click bubbling from marker to map
I have:
* marker with popup
* map click handler (for geocoding)

When I click on marker I've got 'click' event on both map and marker.
So popup opened (ok) and geocoding start working (wrong!).

Why event from marker propagates to underlying  map?
How I can prevent this?

### PR DESCRIPTION
**Pull request by yohanboniface**
Fix #3604.
I had a quick break.
Bubbling from marker is supposed to be the default, now, so I just stopped the event on `_openPopup`.
I could also just add it on `bindPopup`, if you prefer this pattern.

### CODE REVIEW

**Comment by mourner** [comment]
> Bubbling from marker is supposed to be the default, now

Hmm, but why? I think I'd prefer to keep not bubbling up from markers the default.

**Comment by yohanboniface** [comment]
> Hmm, but why?

The map is an event target, so it's considered while traversing the DOM, and given that it listens for `click` the event is fired.

> I think I'd prefer to keep not bubbling up from markers the default.

Are we sure it's a problem (out of retrocompat) ? It's closer to DOM behaviour, no?

**Comment by ktoto** [comment]
@yohanboniface problem not in `openPopup`. problem happen when i have 'click' handler in marker and in map.
`openPopup` just is special case with this binding.

**Comment by yohanboniface** [comment]
@ktoto (take this with caution, as it's not fully decided): with the current code when you listen to a click event and you don't want the map to also receive it, you are responsible of stopping it.
In the case of `bindPopup`, given that the event listener has been added by Leaflet internally, it's its responsibility to then stop it. Makes sense?

**Comment by ktoto** [comment]
@yohanboniface but before #3307 all be fine. I just want to understand why logic with map is changed?
Why `map` want `click` if the first interaction element was `marker`? Why just not stop on `marker` at all?

**Comment by yohanboniface** [comment]
>  Why map want click if the first interaction element was marker? Why just not stop on marker at all?

Just like in normal DOM, when an event is fired by an element, all its ancestors get it, unless `stopPropagation` is called at some point.
You may have a use case where you want to catch all `click` events, both on markers (or polygons) and map.

**Comment by mourner** [comment]
I'd rather not follow DOM conventions and do an exception here, since I can't think of a use case where you'd want to trigger both map and marker on marker click, but people will have a very hard time adjusting to this breaking change.

**Comment by yohanboniface** [comment]
> I'd rather not follow DOM conventions and do an exception here

You mean exception for marker or for `click` ? i.e. never bubble `click` or never bubble `click` on marker but still bubble it on polygons?
I can think of many use cases where I'd love to receive `click` events that where initially fired on a polygon. And by the way, being able to receive `click` on a map whatever the source was would be a killer simplification for all "drawing" application on the map.
But you decide :)

**Comment by mourner** [comment]
Exception for marker specifically, as opposed to vector layers and image overlays (which can be perceived as "click through" in some interfaces).

**Comment by yohanboniface** [comment]
OK, I'll do that asap :)

**Comment by yohanboniface** [comment]
@mourner only for `click` or we can think about other events?

**Comment by mourner** [comment]
@yohanboniface let's follow the 0.7.3 behavior here.

File: src/core/Events.js [hunk 1]
```diff
@@ -4,6 +4,10 @@
 
 L.Evented = L.Class.extend({
 
+	options: {
+		unpropagateEvents: ''  // Space separated events that should not be propagated
+	},
+
```
Comment (mourner) [inline src/core/Events.js]: This should be in `Layer`.

File: src/layer/marker/Marker.js [hunk 2]
```diff
@@ -6,6 +6,7 @@ L.Marker = L.Layer.extend({
 
 	options: {
 		pane: 'markerPane',
+		unpropagateEvents: 'click dblclick mouseover mouseout contextmenu',
```
Comment (mourner) [inline src/layer/marker/Marker.js]: Is there a better option name? Maybe `stopEvents` or `nonBubblingEvents`.

File: src/map/Map.js [hunk 3]
```diff
@@ -696,7 +696,8 @@ L.Map = L.Evented.extend({
 		for (var i = 0; i < targets.length; i++) {
 			if (targets[i].listens(type, true)) {
 				targets[i].fire(type, data, true);
-				if (data.originalEvent._stopped) { return; }
+				if (data.originalEvent._stopped
+					|| (targets[i].options.unpropagateEvents && targets[i].options.unpropagateEvents.indexOf(type) !== -1)) { return; }
```
Comment (mourner) [inline src/map/Map.js]: `click` will be a false positive if you have `dblclick` non-bubbling.

Comment (yohanboniface) [inline src/map/Map.js]: Huuuu, good catch! Should we switch to using an array instead? Not sure about perfs :/

File: src/layer/marker/Marker.js (hunk 2 above)
Comment (yohanboniface) [inline src/layer/marker/Marker.js]: `nonBubblingEvents` better to me too, I'll update

File: src/core/Events.js (hunk 1 above)
Comment (yohanboniface) [inline src/core/Events.js]: I hesitated ;)

File: src/map/Map.js [hunk 4]
```diff
@@ -696,7 +696,8 @@ L.Map = L.Evented.extend({
 		for (var i = 0; i < targets.length; i++) {
 			if (targets[i].listens(type, true)) {
 				targets[i].fire(type, data, true);
-				if (data.originalEvent._stopped) { return; }
+				if (data.originalEvent._stopped
+					|| (targets[i].options.nonBubblingEvents && targets[i].options.nonBubblingEvents.indexOf(type) !== -1)) { return; }
```
Comment (mourner) [inline src/map/Map.js]: Unfortunately IE only supports array indexOf starting from 9. We'll probably have to iterate over the array in a loop.

Comment (yohanboniface) [inline src/map/Map.js]: Gasp :/
Should I add a polyfill `L.Util.inArray` for that? To make the code shorter here and more readable.

Comment (mourner) [inline src/map/Map.js]: Yeah, maybe something like `L.Util.indexOf`.

Comment (yohanboniface) [inline src/map/Map.js]: `L.Util.indexOf` seems meaning it also will work on strings, is that what we want?

Comment (mourner) [inline src/map/Map.js]: It's fine to keep only for arrays since string indexOf doesn't need an util method. It's an internal utility after all, we don't have to make it generic.

Comment (yohanboniface) [inline src/map/Map.js]: OK done :)

File: src/core/Util.js [hunk 5]
```diff
@@ -147,6 +147,13 @@ L.Util = {
 		return (Object.prototype.toString.call(obj) === '[object Array]');
 	},
 
+	indexOf: Array.indexOf || function (array, el) {
```
Comment (mourner) [inline src/core/Util.js]: There's no `Array.indexOf` :)

**Comment by yohanboniface** [comment]
Meeeeehhhh, how the console is playing with me!?
screenshot from 2015-07-09 13 50 10

`Array.prototype.indexOf`?

**Comment by mourner** [comment]
Mine is like this :)
image
I think we're fine just not using native indexOf. It's not that much of a difference.

**Comment by yohanboniface** [comment]
Yeah, Chrome vs FF :/
OK, I make the loop for everybody :)

**Comment by mourner** [comment]
Actually I think it's fine at this moment :)

**Comment by mourner** [comment]
OK, let's rebase now.

**Comment by yohanboniface** [comment]
> Actually I think it's fine at this moment :)
Humm, not sure which moment :p Seems I've commit one second before to remove the use of Array.indexOf

**Comment by mourner** [comment]
Nevermind :)

**Comment by yohanboniface** [comment]
Rebased and green :)
