### PR TITLE
Fixes event target of popupopen event and adds test

### LINKED ISSUE #8558: Incorrect marker popupopen event e.target reference
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

[https://codepen.io/philiplarner/pen/zYjyGdY](https://codepen.io/philiplarner/pen/zYjyGdY)

1. Hover the red marker (A)

### Expected behavior

It should raise an alert referencing marker A as it does in older versions of leaflet? 

To see please adjust the leaflet version 1.7.1 ("Settings" in the header > "Pen Settings" > "JS" and adjust version number)

### Current behavior

The alert from marker A references marker B

### Minimal example reproducing the issue

https://codepen.io/philiplarner/pen/zYjyGdY

### Environment

- Leaflet version: 1.9.2
- Browser (with version): Chrome
- OS/Platform (with version): Windows 10

I think there is an issue with leaflet "popupopen" event starting at version 1.8.0. When you programmatically close a popup and open it, triggering the "popupopen" event on a specific marker when it opens: the event target doesnt match what the event was bound on? N.B this is when all markers share the same popup instance

### PR DESCRIPTION
**Pull request by Belair34**
The main issue was that _prepareOpen in DivOverlay was changed so that it didn't have any logic to select the correct source. Let me know if anything should be changed/refactored.
Fixes #8558

### CODE REVIEW

File: src/layer/DivOverlay.js [hunk 1]
```diff
@@ -230,23 +230,20 @@ export var DivOverlay = Layer.extend({
...
+		var source = parent;
 		if (!source._map) { return false; }
 
 		if (source instanceof FeatureGroup) {
 			source = null;
-			var layers = this._source._layers;
+			var layers = parent._layers;
 			for (var id in layers) {
-				if (layers[id]._map) {
+				if (layers[id]._map && (Number(id) === this._source._leaflet_id || this._source instanceof FeatureGroup)) {
```
Comment (IvanSanchez) [inline src/layer/DivOverlay.js:241]: I'd rather use the `stamp` function from `Util`, instead of querying `_leaflet_id`. It's what the codebase currently does. 

The only reason not to do so would be a use case where `this._source` is not a `L.Layer` - I don't think that's possible here.

File: src/layer/Popup.js [hunk 2]
```diff
@@ -420,7 +420,7 @@ Layer.include({
 	// @method openPopup(latlng?: LatLng): this
 	// Opens the bound popup at the specified `latlng` or at the default popup anchor if no `latlng` is passed.
 	openPopup: function (latlng) {
-		if (this._popup && this._popup._prepareOpen(latlng || this._latlng)) {
+		if (this._popup && this._popup._prepareOpen(latlng || this._latlng, this)) {
```
Comment (Falke-Design) [inline src/layer/Popup.js:423]: It would be enough to do `this._popup._source = this;`

**Review by Falke-Design — CHANGES_REQUESTED** [review]
The test is great, but I think the other changes are not necessary. It would be enough to do  `this._popup._source = this;` in `openPopup` & `openTooltip`

File: src/layer/DivOverlay.js (hunk 1 above)
Comment (Belair34) [reply src/layer/DivOverlay.js]: @Falke-Design That was both to select the correct layer as well as to preserve the behavior of FeatureGroups. However, your idea was a better way to select the correct layer; I just had to add a little bit to it to preserve FeatureGroup behavior.

File: src/layer/Popup.js [hunk 3]
```diff
@@ -420,10 +421,14 @@ Layer.include({
...
 	// Opens the bound popup at the specified `latlng` or at the default popup anchor if no `latlng` is passed.
 	openPopup: function (latlng) {
-		if (this._popup && this._popup._prepareOpen(latlng || this._latlng)) {
-
-			// open the popup on the map
-			this._popup.openOn(this._map);
+		if (this._popup) {
+			if (!(this instanceof FeatureGroup)) {
+				this._popup._source = this;
+			}
```
Comment (Falke-Design) [inline src/layer/Popup.js:427]: I still don't understand it, but I think it has it reason. Can you please add a test for this?

**Review by Falke-Design — CHANGES_REQUESTED** [review]

File: src/layer/DivOverlay.js [hunk 4]
```diff
@@ -260,6 +260,7 @@ export var DivOverlay = Layer.extend({
 				throw new Error('Unable to get source layer LatLng.');
 			}
 		}
+
```
Comment (Falke-Design) [inline src/layer/DivOverlay.js:263]: Please revert this

File: src/layer/Popup.js (hunk 3 above)
Comment (Belair34) [reply src/layer/Popup.js:427]: I'm not sure what kind of test I could add, but without this if statement there are 4 existing tests that fail. They all seem to relate to feature groups of popups/tooltips with functions as content (in bindTooltip/bindPopup).

**Review by Falke-Design — APPROVED** [review]

**Review by IvanSanchez — APPROVED** [review]

**Comment by plarner30** [comment]
hey many thanks for the fix do you guys know if there will be a new minor release any time soon?

**Comment by jonkoops** [comment]
@plarner30 see #8634
