### PR TITLE
Revamp synthetic dblclick event instantiation

### LINKED ISSUE #8631: Double click on an input element that is rendered on the leaflet map
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Perform a double click on the input element and move the mouse between the clicks within the input.

It might require a few tries to do it, but it should be fairly easy to reproduce

### Expected behavior

That the error does not happen

### Current behavior

An error is thrown in the console:

```
Permission denied to access property "bind"
```

Image of the error:

image

### Minimal example reproducing the issue

https://codesandbox.io/s/amazing-oskar-c0cxuc

### Environment

- Leaflet version: 1.8.0, 1.9.0, 1.9.1, 1.9.2
- Browser (with version): Firefox >= 105
- OS/Platform (with version): Windows 11, MacOS 12.6.1

### Extra info

- This issue does not happen on Chrome/Edge

Edit: added the `Extra info` section

### PR DESCRIPTION
**Pull request by IvanSanchez**
This is a ~~blind (i.e. totally untested)~~ attempt to fix #8631.

I'm just using my code pattern for initializing synthetic events (from https://gitlab.com/IvanSanchez/gleo/-/blob/master/src/Platina.mjs#L1109 ) - instead of iterating through the properties of the existing event, this creates a init dictionary with the properties defined in the DOM specs.

This might not be the best solution, though. Perhaps the "DOM event cloning" functionality should be moved to `DomEvent.js`, and be called from the dblclick code.

### CODE REVIEW

File: src/dom/DomEvent.DoubleTap.js [hunk 1]
```diff
@@ -49,10 +50,12 @@ function makeDblclick(ev) {
 			pointerType: ev.pointerType,
 			isPrimary: ev.isPrimary,
 		};
-		return new PointerEvent('dblclick', init);
+		newEvent = new PointerEvent('dblclick', init);
 	} else {
-		return new MouseEvent('dblclick', init);
+		newEvent = new MouseEvent('dblclick', init);
 	}
+	newEvent._simulated = true; // for debug purposes
```
Comment (IvanSanchez) [inline src/dom/DomEvent.DoubleTap.js:57]: I'm not sure that we need this anymore.

Comment (Falke-Design) [reply src/dom/DomEvent.DoubleTap.js:57]: My understanding is that we have this property to see in the tests from where the event is fired. Have we another way to check if it is a Leaflet created event?

File: src/dom/DomEvent.DoubleTap.js [hunk 2]
```diff
@@ -65,7 +99,7 @@ export function addDoubleTapListener(obj, handler) {
 		if (now - last <= delay) {
 			detail++;
 			if (detail === 2) {
-				handler(makeDblclick(e));
+				ev.target.dispatchEvent(makeDblclick(ev));
```
Comment (Falke-Design) [inline src/dom/DomEvent.DoubleTap.js:102]: Are you sure that this results in the same?

Comment (IvanSanchez) [reply src/dom/DomEvent.DoubleTap.js:102]: It's not "the same". It's... better. Now the event handlers do receive an instance of `MouseEvent` or `PointerEvent` instead of an empty object with copied properties. So the propagation & cancellation logic is the browser's native one. In other words: synthetic `dblclick` events will propagate through the DOM.

AFAIK this couldn't be done before, as browsers didn't have consistent behaviour for `PointerEvent`s, and/or different ways of instantiating synthetic events.

File: src/dom/DomEvent.DoubleTap.js (hunk 1 above)
Comment (IvanSanchez) [reply src/dom/DomEvent.DoubleTap.js:57]: No, there's not. A synthetic event dispatched from Leaflet looks and behaves exactly the same as a synthetic event dispatched from Happen, or from Prosthetic-Hand (the libraries used in the automated tests).

File: src/dom/DomEvent.DoubleTap.js (hunk 2 above)
Comment (Falke-Design) [reply src/dom/DomEvent.DoubleTap.js:102]: Okay yeah I understand now. Is much more cleaner now!

File: src/dom/DomEvent.DoubleTap.js (hunk 1 above)
Comment (Falke-Design) [reply src/dom/DomEvent.DoubleTap.js:57]: We don't need this anymore. The event is now fired over the browser to the target, so the event self is not simulated.

File: src/dom/DomEvent.DoubleTap.js [hunk 3]
```diff
@@ -7,19 +7,53 @@ import * as DomEvent from './DomEvent';
...
+		};
+		newEvent = new PointerEvent('dblclick', init);
+	} else {
+		newEvent = new MouseEvent('dblclick', init);
 	}
-	event = newEvent;
-	newEvent.type = 'dblclick';
-	newEvent.detail = 2;
-	newEvent.isTrusted = false;
 	newEvent._simulated = true; // for debug purposes
```
Comment (Falke-Design) [inline src/dom/DomEvent.DoubleTap.js:57]: Let us remove this line again

**Review by Falke-Design — CHANGES_REQUESTED** [review]
Looks good for me. 
Should we add a test for the case #8631?

**Review by Falke-Design — APPROVED** [review]
