### PR TITLE
Fix TileLayer._update so it doesn't break drag-then-pinch interactions.

### LINKED ISSUE #3814: One-finger pan + two-finger zoom in = broken tiles on master
To reproduce, follow the instructions on #3798, and zoom **in** a couple of times. Tiles at the appropriate zoom level do not load (former tiles or grey space is seen instead).

Reproducible on Chrome on Android:
img_20150907_160642

And on Safari on iPad:

img_20150907_162016

And obviously we love windows phone:

img_20150907_162503

Obvious first place to look is the pinch-zoom interaction, about how the first two finger points are loaded.

Not a duplicate of #3798 because this affects loading of tile layers, not display of vectors.

Might or might not be related to #3765, #3659, #3683.

### PR DESCRIPTION
**Pull request by IvanSanchez**
Fixes #3814.

So `_update` was using a rounded zoom level, but internally there were calls to `createTile`, which depended on `this._tileZoom`. The result was that, after a drag-then-pinch interaction, if a tile to be loaded had a index `x:y:z`, the URL would be `z+1/y/x` (or z-1), but the key stayed the same - which was breaking havoc on the tile loading/unloading algorithm.

### CODE REVIEW

File: src/layer/tile/GridLayer.js [hunk 1]
```diff
@@ -431,12 +431,8 @@ L.GridLayer = L.Layer.extend({
 
 		if (center === undefined) { center = map.getCenter(); }
 		if (zoom === undefined) { zoom = map.getZoom(); }
-		var tileZoom = Math.round(zoom);
 
-		if (tileZoom > this.options.maxZoom ||
-			tileZoom < this.options.minZoom) { return; }
```
Comment (yohanboniface) [inline src/layer/tile/GridLayer.js]: I don't get why you remove this check

Comment (IvanSanchez) [inline src/layer/tile/GridLayer.js]: Somehow I assumed that check was already wherever `this._tileZoom` was being calculated. Apparently it is not.

**Comment by IvanSanchez** [comment]
Note to self: check out examples with `maxZoom`, `minZoom` and `maxNativeZoom`, and see why the unit tests fail at gridlayer unused zoom levels.

File: src/layer/tile/GridLayer.js [hunk 2]
```diff
@@ -446,11 +449,13 @@ L.GridLayer = L.Layer.extend({
 			this._tiles[key].current = false;
 		}
 
+		if (zoom < this.options.minZoom) { return; }
```
Comment (IvanSanchez) [inline src/layer/tile/GridLayer.js]: I changed `_update` so it works on the gridlayer's "active zoom pyramid level" only, which is good. But if a tile layer has e.g. `minZoom=16` and the map is at zoom e.g. 2, then the code would generate a few million ``s, then try to delete them later.

No check is needed for `maxZoom` because I really don't care about creating *fewer* tiles than normal, then deleting them.

Comment (mourner) [inline src/layer/tile/GridLayer.js]: > then the code would generate a few million s, then try to delete them later.

That sounds horrible.

Comment (IvanSanchez) [inline src/layer/tile/GridLayer.js]: Yeah, that's why I added that check :-)

Comment (IvanSanchez) [inline src/layer/tile/GridLayer.js]: Yeah, that's why I added that check :-)

**Comment by IvanSanchez** [comment]
There is a worrying edge case. In a big enough tablet it's possible to pinch-zoom out 5 or 6 levels at once. This means that the first `_update` will run with `this._tileZoom` 5 or 6 times greater than `map._zoom`, and that will create 4^5 to 4^6 temporary tiles, that will be removed by `_abortLoading` when the second `_update` is run (when the zoom animation ends).

It works, except for the fact that it an crash an iPad.

I'm guessing it might be a good idea to prevent tiles from loading if the tilelayer's `_tileZoom` differs from the map's zoom level by more than a threshold - maybe 1, maybe `map.options.zoomAnimationThreshold`. This would replace the `minZoom` check in `_update`.

**Comment by IvanSanchez** [comment]
A threshold of more than 1 zoom levels to cancel a `GridLayer._update` does the trick, so I've amended the commit.

**Comment by IvanSanchez** [comment]
I think this fixes #3515 as well :-D

File: src/layer/tile/TileLayer.js [hunk 3]
```diff
@@ -56,8 +56,8 @@ L.TileLayer = L.GridLayer.extend({
 	createTile: function (coords, done) {
 		var tile = document.createElement('img');
 
-		tile.onload = L.bind(this._tileOnLoad, this, done, tile);
-		tile.onerror = L.bind(this._tileOnError, this, done, tile);
+		L.DomEvent.on(tile, 'load', L.bind(this._tileOnLoad, this, done, tile));
+		L.DomEvent.on(tile, 'error', L.bind(this._tileOnError, this, done, tile));
```
Comment (IvanSanchez) [inline src/layer/tile/TileLayer.js]: Firefox has real issues with `.onload`. It just doesn't fire during a `flyTo` animation, but somehow `L.DomEvent.on('load',...)` works flawlessly.

File: src/layer/tile/GridLayer.js [hunk 4]
```diff
@@ -356,13 +361,17 @@ L.GridLayer = L.Layer.extend({
...
 				this._update(center, tileZoom);
 			}
 
 			if (!noPrune) {
 				this._pruneTiles();
 			}
+
+			// Flag to prevent _updateOpacity from pruning tiles during
+			// a zoom anim or a pinch gesture
+			this._noPrune = !!noPrune;
```
Comment (IvanSanchez) [inline src/layer/tile/GridLayer.js]: During a pinch gesture, if the user zooms in, the tile the event started on might be destroyed because `_onTileLoad` will call `_updateOpacity` which will call `_pruneTiles`, which checks parent/child tiles and prunes them if needed.

File: src/layer/tile/GridLayer.js [hunk 5]
```diff
@@ -343,10 +343,15 @@ L.GridLayer = L.Layer.extend({
...
+		var tileZoom = Math.round(zoom);
+		if ((this.options.maxZoom !== undefined && tileZoom > this.options.maxZoom) ||
+		    (this.options.minZoom !== undefined && tileZoom < this.options.minZoom)) {
+			tileZoom = undefined;
+		}
+
+		var tileZoomChanged = (tileZoom !== this._tileZoom);
 
-		if (!noUpdate && tileZoomChanged) {
+		if (!noUpdate || tileZoomChanged) {
```
Comment (IvanSanchez) [inline src/layer/tile/GridLayer.js]: If animating, ignore the `noUpdate` flag and reload tiles anyway if we're switching the grid layer to another level. This way there's no need to throttle!

File: src/layer/tile/GridLayer.js [hunk 6]
```diff
@@ -446,11 +451,13 @@ L.GridLayer = L.Layer.extend({
 			this._tiles[key].current = false;
 		}
 
+		if (Math.abs(zoom - this._tileZoom) > 1) { this._setView(center, zoom); }
```
Comment (yohanboniface) [inline src/layer/tile/GridLayer.js]: Maybe a comment here would help future maintainers (with mantra "say why not what" in mind, of course) ?

**Comment by yohanboniface** [comment]
Is #3811 also taken into account?

**Comment by IvanSanchez** [comment]
@yohanboniface No, and I've just noticed that I've somehow broken `_getTiledPixelBounds` for fractional zoom. :-(
