### PR TITLE
Add `getWheelPxFactor` and fix test `changes the option 'wheelPxPerZoomLevel'` for mac

### LINKED ISSUE #8479: `wheelPxPerZoomLevel` unit test always fails on Mac
The last unit test in `Map.ScrollWheelZoomSpec.js` added by @Falke-Design always fails for me locally on Mac:

```
Firefox 105.0 (Mac OS 10.15) Map.ScrollWheelZoom changes the option 'wheelPxPerZoomLevel' FAILED
	Error: expected 1 to be above 1 (node_modules/expect.js/index.js:96)
```

We should figure out if it's expected to fail and fix either the behavior of the test, making it more platform-agnostic.

### PR DESCRIPTION
**Pull request by Falke-Design**
Fixes #8479

The problem was the `devicePixelRatio`. 
I made now `getWheelPxFactor` public.

### CODE REVIEW

File: src/dom/DomEvent.js [hunk 1]
```diff
@@ -263,23 +263,24 @@ export function getMousePosition(e, container) {
...
 
+// @function getWheelPxFactor(): Number
+// Gets the wheel pixel factor based on the devicePixelRatio
+export function getWheelPxFactor() {
+	// We need double the scroll pixels (see #7403 and #4538) for all Browsers
+	// except OSX (Mac) -> 3x, Chrome running on Linux 1x
+	return (Browser.linux && Browser.chrome) ? window.devicePixelRatio :
+		Browser.mac ? window.devicePixelRatio * 3 :
+		window.devicePixelRatio > 0 ? 2 * window.devicePixelRatio : 1;
+}
```
Comment (mourner) [inline src/dom/DomEvent.js:274]: Does this have to be a function, or could we export a constant instead?

Comment (Falke-Design) [reply src/dom/DomEvent.js:274]: I think a constant would be ok too. I didn't know if we want to have constants in `DomEvent` so I created a function.

Thinking loud: What if the user zooms on the page (not map) and changes the `devicePixelRatio`? With a function we would always have the correct value. How much performance costs do we have with a function instead of a constant?

Comment (mourner) [reply src/dom/DomEvent.js:274]: Yeah, devicePixelRatio possibly changing is a good point. Let's keep it a function then.

File: src/dom/DomEvent.js [hunk 2]
```diff
@@ -263,23 +263,24 @@ export function getMousePosition(e, container) {
...
 }
 
+// @function getWheelPxFactor(): Number
+// Gets the wheel pixel factor based on the devicePixelRatio
+export function getWheelPxFactor() {
+	// We need double the scroll pixels (see #7403 and #4538) for all Browsers
+	// except OSX (Mac) -> 3x, Chrome running on Linux 1x
+	return (Browser.linux && Browser.chrome) ? window.devicePixelRatio :
+		Browser.mac ? window.devicePixelRatio * 3 :
+		window.devicePixelRatio > 0 ? 2 * window.devicePixelRatio : 1;
```
Comment (mourner) [inline src/dom/DomEvent.js:273]: Nit: I don't like the repetition.

```suggestion
	var ratio = window.devicePixelRatio;
	return Browser.linux && Browser.chrome ? ratio :
		Browser.mac ? ratio * 3 :
		ratio > 0 ? 2 * ratio : 1;
```

**Review by mourner — APPROVED** [review]

**Comment by jonkoops** [comment]
@Falke-Design is this something that needs a backport to `v1`?

**Comment by Falke-Design** [comment]
No need but doesn't hurt if we do

**Comment by jonkoops** [comment]
Good to know. Just wanted to know if we were missing any essential fixes.
