### PR TITLE
Fix zoom animation freeze race condition

### LINKED ISSUE #2693: Map freeze problem, but unlocks after marker click
Hello

I'm using leaflet 0.7.2 in a windows RT application, developed with the use of the WinJS library. I'm also using angularjs as the basis for the application. The map freezes 1/20 times when i zoom in or out. When i press a marker on the map, the map unfreezes and becomes responsive once more. When i use the leaflet-src and debug the problem i notice, that when the problem occurs the "_catchTransitionEnd"  isn't called. When i press a marker the "_catchTransitionEnd" is called and the map unfreezes. Does anyone know what is causing this problem, and better still how to fix it? a quick workaround would be great, because of the deadline i'm on.

Any help would be greatly appreciated.

Thanks in advance

Ian

### PR DESCRIPTION
**Pull request by mourner**
In theory, this closes #2693 and #2478. Should be tested after fixing #3268 though, since pinch-zoom on iOS is currently broken.

### CODE REVIEW

File: src/map/anim/Map.ZoomAnimation.js [hunk 1]
```diff
@@ -34,7 +34,15 @@ L.Map.include(!zoomAnimated ? {} : {
 		this._panes.mapPane.appendChild(proxy);
 
 		this.on('zoomanim', function (e) {
+			var prop = L.DomUtil.TRANSFORM,
+				transform = proxy.style[prop];
+
 			L.DomUtil.setTransform(proxy, this.project(e.center, e.zoom), this.getZoomScale(e.zoom, 1));
+
+			// workaround for case when transform is the same and so transitionend event is not fired
+			if (transform === proxy.style[prop] & this._animatingZoom) {
```
Comment (uniphil) [inline src/map/anim/Map.ZoomAnimation.js]: should that be an `&&` in the if?

Comment (danzel) [inline src/map/anim/Map.ZoomAnimation.js]: @mourner ^^

Comment (mourner) [inline src/map/anim/Map.ZoomAnimation.js]: Yep, good catch
