### PR TITLE
Fix Marker position while zooming

### LINKED ISSUE #5181: Marker.setLatLng sets x and y based on pre-zoom projection during zoom animation.
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported
  * I tried but there might be duplicates. Maybe I'm not using the right keywords.

----

When putting animated overlays or markers on map, during the zoom transition those animations will look off because the underlying tiles pane translate and make the marker or overlay look off location. 

For example [Leaflet Ant Path](http://rubenspgcavalcante.github.io/leaflet-ant-path/) looks bad during zoom transition:

lag

[Leaflet Animated Marker](http://openplans.github.io/Leaflet.AnimatedMarker/) is suffering from similar issue:

bike

I think Leaflet should provide an API that allows markers and overlays attach themselves to the element that zoom CSS transition is applied to so they are scaled with the tiles layer.

### LINKED ISSUE #5505: Marker events fired when zooming causing markers to move to preceding offset, then to the correct screen location.
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: W10

0. Zoom between 14-16 to see this effectively.
1. Create a new marker with default settings. To make life easier, create this marker on a click event.
2.  As the marker is created, zoom out 1 level. The marker should jump to the preceding screen offset, and then adjust itself to the current zoom level.

This may take a few tries. I've noticed it occuring semi-frequently when pinging new markers to my Leaflet app from a TCP server. When a new location arrives from the server, a marker is created and then added to the map. Zooming out anywhere in this process causes it to jump.

### LINKED ISSUE #5994: Marker drifts on zoom / marker jumps around on zoom
Issue 1. Marker drifts on zoom (does not stay centered on the map, when marker and map is on same coordinates)
Reproduce: go to https://jsfiddle.net/o0yfm5zy/1/
Click button **first**, and then zoom. 

Issue 2. marker jumps around on zoom (only about a pixel or so but it is noticeable, especially when you use flyTo() on retina screen).
Reproduce: on the jsfiddle, click the button again (or re-run) and zoom

I experience the same behaviour on firefox, chromium/opera and ios.

### LINKED ISSUE #7017: Marker drifts if setLatLng() is called during a zoom animation
Example: [jsfiddle](http://jsfiddle.net/cwad8p4m/1/)

**Steps to reproduce**
 - Add a marker with a custom icon (including iconSize and iconAnchor)
 - Update the markers position with `setLatLng` in an interval

**Expected behavior**
 - While zooming i'd expect the marker to maintain it's geographical position

**Current behaviour**
 - The marker drifts along it's screen position (similar to how a custom icon without setting an iconAnchor will drift).  It should be pretty apparent when you scoll wheel zoom in that fiddle.

**Additional context**
I'm writing a satellite overlay where the markers position changes rapidly and it needs a custom icon.

### PR DESCRIPTION
**Pull request by Falke-Design**
If a marker is set to a new latlng while zooming the marker jumps around. The problem is that the `this._pixelOrigin` (which is used for the calculation of the marker position) is only set after the zoom (`_onZoomTransitionEnd`), so while zooming the old pixelOrigin is used and the marker jumps. 

I tried to create a test but it was not possible.

- Fixes #7017
- Fixes #5181
- Fixes #5505
- Fixes #5994 (It describes exactly that issue but I'm not abel to reproduce it with the demo)

New src: [link](https://florianbischof.net/leaflet/marker-zoom/leaflet-src.js)

marker_jumping_wrong

Fixed:
marker_jumping_fix

### CODE REVIEW

File: src/map/Map.js [hunk 1]
```diff
@@ -1697,6 +1700,12 @@ export var Map = Evented.extend({
 			noUpdate: noUpdate
 		});
 
+		if (!this._tempFireZoomEvent) {
+			this._tempFireZoomEvent = this._zoom !== this._animateToZoom;
```
Comment (Falke-Design) [inline src/map/Map.js:1704]: we need to store if the zoom is different, to fire later the `zoom` event.

File: src/map/Map.js [hunk 2]
```diff
@@ -1697,6 +1700,12 @@ export var Map = Evented.extend({
 			noUpdate: noUpdate
 		});
 
+		if (!this._tempFireZoomEvent) {
+			this._tempFireZoomEvent = this._zoom !== this._animateToZoom;
+		}
+
+		this._move(this._animateToCenter, this._animateToZoom, undefined, true);
```
Comment (Falke-Design) [inline src/map/Map.js:1707]: This is the necessary call to set the `_pixelOrigin` but we need to prevent firing the `zoom` event (to keep the current behaviour)

**Review by mourner — APPROVED** [review]
Nice!

**Comment by mitow7821** [comment]
@Falke-Design In 1.8 leaflet version this problem occurs with permanent tooltip bound to that marker.
