### PR TITLE
Fix L.Evented.listens() on removed event handlers, #4474

### LINKED ISSUE #4474: L.Evented: when a listener is removed with it's function, "listens" still returns true
Testcase:
```javascript
var m = new L.Marker();
var handler = function() {console.log("event fired")};

m.on("test", handler);     // register
m.fire("test");            // fires

console.log(m.listens("test"));    // returns true

m.off("test", x);                  // remove listener 
console.log(m.listens("test"));    // still returns true!
m.fire("test");                    // but doesn't fire anymore!
```

https://playground-leaflet.rhcloud.com/rog/edit?html,js,output

### PR DESCRIPTION
**Pull request by IvanSanchez**
Fixes #4474. cc @fab1an

### CODE REVIEW

**Comment by IvanSanchez** [comment]
Hmm. Apparently this breaks an existing unit test.

**Comment by IvanSanchez** [comment]
0836527 was weird. Apparently the `expect` helpers for `nearLatLng` were **never** working, and a race condition in the unit test itself (async calls to `expect()` with no `done()` callback) were skipping the checks and running them out of order.

This looks good to me, but definitely needs another pair of eyes.

File: src/core/Events.js [hunk 1]
```diff
@@ -159,6 +159,9 @@ L.Evented = L.Class.extend({
 					}
 				}
 			}
+			if (listeners.length === 0) {
```
Comment (yohanboniface) [inline src/core/Events.js]: I'd move this in the previous `if`, because it seems to me that we only want to check `length` if `listeners` is not `undefined`/`null`.

File: spec/suites/layer/marker/MarkerSpec.js [hunk 2]
```diff
@@ -237,17 +237,19 @@ describe("Marker", function () {
...
 		});
 
-		it("do not catch event if it does not listen to it", function () {
+		it("do not catch event if it does not listen to it", function (done) {
 			var marker = new L.Marker([55, 37]);
 			map.addLayer(marker);
 			marker.once('mousemove', function (e) {
 				// It should be the marker coordinates
-				expect(e.latlng).to.be.nearLatLng(marker.getLatLng());
+				expect(e.latlng.equals(marker.getLatLng())).to.be.equal(true);
```
Comment (yohanboniface) [inline spec/suites/layer/marker/MarkerSpec.js]: Why `to.be.equal(true)` and not simply `to.be(true)`?
(And why not just `assert e.latlng == marker.getLagLng()`? Ah, we are not in python, sorry ;))

Comment (IvanSanchez) [inline spec/suites/layer/marker/MarkerSpec.js]: Not really sure. We're using a custom version of `expect.js`, and the behaviour of `to.be` and `to.be.equal` and `to.eql` is *funny*. We could see if changing to a NPM package for this would make this any better.
