### PR TITLE
Fix implementation for disabling & enabling text selection

### LINKED ISSUE #8740: Fix `userSelect` on Safari
#8738 removed prefixing for `userSelect`, but Webkit (Safari on iOS and desktop) still has it prefixed (`WebkitUserSelect`) and doesn't support the non-prefixed version.

Let's bring it back and make sure we're more careful about this, checking support on MDN / CanIUse before making similar changes. No need to bring back #8739 — can be a simple ternary.

### PR DESCRIPTION
**Pull request by jonkoops**
Changes the implementation of `DomUtil.disableTextSelection()` and `DomUtil.enableTextSelection()` to exclusively use the [`user-select`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) CSS property.

Previously this was detecting the `selectstart` event and then using `event.preventDefault()` to ensure the user was not able to select text. This approach however was flawed as Safari on iOS now supports this event, but does not prevent the user from selecting text when the event is prevented.

Also fixes a bug where it was possible to call `DomUtil.disableTextSelection()` twice in a row allowing the internal value for restoring text selection to be incorrectly set to `none`. This then caused `DomUtil.enableTextSelection()` to 'restore' this incorrect value.

Documentation for `DomUtil.disableImageDrag()` and `DomUtil.enableImageDrag()` has also been adjusted as it contained a incorrect references.

Closes #8740

### CODE REVIEW

**Comment by jonkoops** [comment]
Some cross browser testing would be appreciated before merging this one. I've tested this on iOS and macOS Safari (16.2), Firefox (macOS 108.0.1) and Chrome (macOS 108.0.5359.124).

I've added a test HTML file for debugging purposes (see `debug/tests/text-selection.html`).

File: src/dom/DomUtil.js [hunk 1]
```diff
@@ -100,45 +100,38 @@ export function getPosition(el) {
...
-		const style = document.documentElement.style;
-		_userSelect = style.userSelect;
-		style.userSelect = 'none';
-	};
-	enableTextSelection = function () {
-		document.documentElement.style.userSelect = _userSelect;
-		_userSelect = undefined;
-	};
+export function enableTextSelection() {
+	documentStyle[userSelectProp] = prevUserSelect;
```
Comment (Falke-Design) [inline src/dom/DomUtil.js:123]: If `enableTextSelection` is called before `disableTextSelection` it will overwrite the default value `auto`. We should set `prevUserSelect` to `auto` or add a check before setting the value

**Review by Falke-Design — CHANGES_REQUESTED** [review]

File: src/dom/DomUtil.js (hunk 1 above)
Comment (Falke-Design) [reply src/dom/DomUtil.js:123]: Ok it doesn't allow to set invalid values but I still think it would be cleaner

**Comment by Falke-Design** [comment]
> Some cross browser testing would be appreciated before merging this one. I've tested this on iOS and macOS Safari (16.2), Firefox (macOS 108.0.1) and Chrome (macOS 108.0.5359.124).
> 
> I've added a test HTML file for debugging purposes (see `debug/tests/text-selection.html`).

Tested via BrowserStack:
Win 10 & Win 11, Chrome 108, Edge 108, Firefox 108: working
Mac Monterey: Safari 15.6, Chrome 108, Edge 108, Firefox 108: working

File: src/dom/DomUtil.js (hunk 1 above)
Comment (jonkoops) [reply src/dom/DomUtil.js:123]: Agreed, I'll add a check :+1:

**Comment by mourner** [comment]
Do you know why the Windows Chrome CI fails? Haven't seen this error before:

```
'karma' is not recognized as an internal or external command,
operable program or batch file.
Error: Process completed with exit code 1.
```

**Comment by jonkoops** [comment]
> Do you know why the Windows Chrome CI fails? Haven't seen this error before:

It seems to happen on the latest commit on `main` as well, perhaps something has changed in GitHub actions?

**Comment by jonkoops** [comment]
Got a fix for the failures on CI under #8742, they are unrelated to the changes in this PR.

**Review by mourner — APPROVED** [review]

**Comment by jonkoops** [comment]
@Falke-Design can we merge this one as far as you are concerned?

**Review by Falke-Design — APPROVED** [review]
Looks good 👍

File: src/dom/DomUtil.js [hunk 2]
```diff
@@ -100,45 +100,45 @@ export function getPosition(el) {
...
-		const style = document.documentElement.style;
-		_userSelect = style.userSelect;
-		style.userSelect = 'none';
-	};
-	enableTextSelection = function () {
-		document.documentElement.style.userSelect = _userSelect;
-		_userSelect = undefined;
-	};
+export function enableTextSelection() {
+	if (typeof prevUserSelect === 'undefined') {
```
Comment (Falke-Design) [inline src/dom/DomUtil.js:126]: Is there a difference or a benefit to use `typeof prevUserSelect === 'undefined'` instead of `prevUserSelect === undefined`?

Comment (jonkoops) [reply src/dom/DomUtil.js:126]: Don't think it makes any difference. I've had the latter fail in SSR contexts when detecting Web APIs, but that's about it.
